### ISSUE TITLE
Add a "context" var resolving to the verticle context

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-js#15]
Currently it's not possible to obtain directly the verticle context in JavaScript like the vertx object

**Comment by DanielJoyce** [comment]
Currently works fine in 3.3.2

var cfg = Vertx.currentContext().config();

A note to others looking trying to grab configuration passed via -conf

**Comment by StephenOTT** [comment]
@DanielJoyce is there a reason why this conflicts the examples provided in the JS docs ? (https://github.com/vert-x3/vertx-config/issues/39)
