### ISSUE TITLE
NPM module loading issues

### ISSUE THREAD

**Issue by carribus** [vert-x3/vertx-lang-js#16]
I posted this query on the vertx group and was directed here. 

Consuming nodejs modules in verticles seems problematic.
Having had a look at jvm-npm.js, I can see that it is possible somehow, but the following block is confusing me:

Require.paths() lines 194-201:

    if (Require.NODE_PATH) {
      r = r.concat(parsePaths(Require.NODE_PATH));
    } else {
      var NODE_PATH = java.lang.System.getenv.NODE_PATH;
      if (NODE_PATH) {
        r = r.concat(parsePaths(NODE_PATH));
      }
    }

Require.NODE_PATH is set to undefined earlier on, and from what I can tell, java.lang.System.getenv.NODE_PATH will always return undefined.

To give you more context, I have npm installed the colors module and am trying to use it with the following code below. 

var colors = require('colors'); 
console.log('hello'.green); // outputs green text 
console.log('i like cake and pies'.underline.red) // outputs red underlined text 
console.log('inverse the color'.inverse); // inverses the color 
console.log('OMG Rainbows!'.rainbow); // rainbow 
console.log('Run the trap'.trap); // Drops the bass 

When I run, I get the following exception:

javax.script.ScriptException: Error: Cannot find module colors in <eval> at line number 125 at column number 6
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:439)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:401)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:152)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        .
        .
        .

**Comment by purplefox** [comment]
The idea is you can set an environment variable called NODE_PATH to point to your node modules directory on disk, then you can just require any modules from there.

However there was a bug in jvm-npm preventing this being picked up correctly, which I've fixed.
I've added a test for this and it seems to work ok now.
