### ISSUE TITLE
I am getting occasional unit test failure with file not found

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-lang-js#18]
I am occasionally getting unit test failures with a filenotfound exception inside the js jar in the local maven repo dir. When I run the tests once more, it usually disappears. This shows on 2 different CI systems (vertx jenkins and drone.io)

https://gist.github.com/alexlehm/3948f0f71114e23dd064
 the unit test is this file: https://github.com/vert-x3/vertx-mail-service/blob/master/src/test/java/io/vertx/ext/mail/JavascriptTest.java

**Comment by purplefox** [comment]
Is this still an issue Alex?

**Comment by alexlehm** [comment]
I cannot say for sure, the Javascript is not used in the tests anymore. I will do a test manually

**Comment by alexlehm** [comment]
I have created a small project that shows the issue, either I am calling the script in a way that doesn't work or it is not finding the file inside the jar sometimes.

https://drone.io/github.com/alexlehm/vertx-mail-js-test/2
https://github.com/alexlehm/vertx-mail-js-test

**Comment by purplefox** [comment]
Your example is failing because jvm-npm.js in your case is inside the vertx-lang-js that you included as a Maven dependency.

JSRunner is something that is intended to be used inside the vertx-lang-js project where it would be found on the file system.

What is it you're trying to achieve by this example?

**Comment by alexlehm** [comment]
Initially I used that to run Javascript test files in eclipse, if that doesn't work at all, i think we can just close the issue
