### ISSUE TITLE
JavaScript modules are not "hot reloaded" when included with a require(...)

### ISSUE THREAD

**Issue by malbari** [vert-x3/vertx-lang-js#26]
Changes applied on the file system to Javascript files included as modules using "require(...)" by a main javascript verticle are not effective until vert.x is restarted.
It could be usefull to have "hot reload" of Javascript files on modules as it happens for the main Javascript verticle using the "-redeploy" option.
See this link for the details: https://groups.google.com/d/msg/vertx/nG_HxfzrLW4/75cXB8aJ_g8J

**Comment by purplefox** [comment]
Redeploy has been removed from 3.0 now anyway, as there are fundamental issues.
