### ISSUE TITLE
Remove implicit context variable

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-js#33]
This _context_ variable is misleading and does not resolve to the `Verticle` context. Developers should use `Vertx.currentContext()` to get the right verticle context and this _context_ variable does not encourage to do it.

It is not clear what `context` should evaluate to as this variable is shared by several Verticles as it is then cached by the factory once the Nashorn engine has been initialized.

In addition the _context_  variable set by the `JSVerticleFactory#init` method evaluates the current context provided by Vert.x in `VerticleFactory#createVerticle` call. At this moment the _Context_ is a temporary context created by the `DeploymentManager` when it invokes the `executeBlocking` method wrapping the `VerticleFactory#createVerticle` method.

**Comment by purplefox** [comment]
We should probably remove it then.

**Comment by vietj** [comment]
yes, I tried hard to come up with something that works for each verticle by using Nashorn bindings but that does not work.

**Comment by vietj** [comment]
also the unit test for context != null is wrong because it does `typeof context == 'object(` and typeof null is `object` :-(
