### ISSUE TITLE
Classpath resolver displays exception when run for the first time

### ISSUE THREAD

**Issue by marvec** [vert-x3/vertx-lang-js#46]
https://github.com/vert-x3/vertx-lang-js/blob/master/src/main/java/io/vertx/lang/js/ClasspathFileResolver.java#L57

When a Vertx application is run for the first time, the debug-js directory is not present and an ugly exception is shown. Before deleting the directory, the class should first check for the directory presence.

**Comment by marvec** [comment]
Saw that with 3.2.0, but cannot recreate now with master. So closing as false positive ;-)

**Comment by cescoffier** [comment]
Thanks for letting us know !
