### ISSUE TITLE
update JSDoc theme

### ISSUE THREAD

**Issue by StephenOTT** [vert-x3/vertx-lang-js#72]
The current JS docs theme: http://vertx.io/docs/jsdoc/ which is REALLY hard to read and traverse...

Each method name seems to mix in with the "Returns" header, and the nav on the right is really messy to read. 

😢 hurts the brain to read it...

Any plans to update this to something more usable?

**Comment by tsegismont** [comment]
Anything proposal?

**Comment by StephenOTT** [comment]
https://github.com/clenemt/docdash
Or
https://github.com/nijikokun/minami

Just based on google popularity.  Docdash would be a great start

**Comment by tsegismont** [comment]
@pmlopes wdyt?

**Comment by vietj** [comment]
that would be an awesome thing

**Comment by vietj** [comment]
the current theme really lacks of usability

**Comment by StephenOTT** [comment]
+1000 :) yes its very painful to work with at the moment.  Get lost very easily!

**Comment by tsegismont** [comment]
@StephenOTT would you like to contribute this?

**Comment by StephenOTT** [comment]
@tsegismont can you explain what needs to occur to make this PR.  Unfamiliar with your doc gen procedure

**Comment by tsegismont** [comment]
@vietj @cescoffier can you explain how it works for JSDoc? I'm not familiar with it either.

**Comment by pmlopes** [comment]
The JSDoc is generated using the jsdoc3-maven-plugin which is now EOL. Internally it uses jsdoc 3.3.2 if these themes work with jsdoc 3.3.2 then it should be possible to configure it on `vertx-parent`

**Comment by vietj** [comment]
actually now we want to do this in vertx-stack project where the doc is actually generated for JS

**Comment by StephenOTT** [comment]
@pmlopes @vietj soooo whats the direction to go down?

**Comment by vietj** [comment]
for the moment, the published doc is in the vertx-stack/docs pom, so that's the best place to look at.

**Comment by vietj** [comment]
@StephenOTT the build has been updated and now documentation generation happens in this project : you can look at the `vertx-lang-js` artifact and you can see the maven jsdoc plugin there

**Comment by StephenOTT** [comment]
@vietj @pmlopes what are your thoughts on updating to use ESDoc instead of JSDoc?
JSDoc seems to be a pretty dead project compared to EsDoc
https://github.com/esdoc/esdoc

**Comment by StephenOTT** [comment]
also some examples of JsDoc usage with current maven build:

![screen shot 2018-03-13 at 3 48 46 pm](https://user-images.githubusercontent.com/1994838/37375254-22fe6082-26f5-11e8-9e9e-cc1848800f0b.png)
![screen shot 2018-03-13 at 5 51 50 pm](https://user-images.githubusercontent.com/1994838/37375273-335b406c-26f5-11e8-9f41-1bc9762a025a.png)

![screen shot 2018-03-13 at 4 04 42 pm](https://user-images.githubusercontent.com/1994838/37375261-2a7a1de2-26f5-11e8-96c8-3f6d939c5e2d.png)
![screen shot 2018-03-13 at 4 04 58 pm](https://user-images.githubusercontent.com/1994838/37375265-2b951f24-26f5-11e8-94ff-b2949ab0eb69.png)

**Comment by vietj** [comment]
I have no issues switching, I think we used jsdoc back in  time because it was the best option available and we never reconsidered this choice.

esdoc looks cool but we need to make sure that the correct metadata is correct (the tags) unless it can reuse the jsdoc ones

**Comment by vietj** [comment]
I've scheduled this for 3.6.0 release, can you host somewhere a couple of Vert.x docs to show us the result ?
